language: ruby
rvm:
- 2.3.0
- 2.2.4
- 2.1.8
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2
before_install:
  - gem install bundler -v '~> 1.11'
gemfile:
  - gemfiles/40.gemfile
  - gemfiles/41.gemfile
  - gemfiles/42.gemfile
  - gemfiles/50.gemfile
cache:
  - bundler
